### Lab 7 - Hierarchical Clustering

The healthy_lifestyle dataset contains information on lifestyle measures such as amount of sunshine, pollution, and happiness levels for 44 major cities around the world. Apply agglomerative clustering to the cities' number of hours of sunshine and happiness levels using both sklearn and SciPy.

Import the needed packages for agglomerative clustering from sklearn and SciPy.
Initialize and fit an agglomerative clustering model using sklearn's AgglomerativeClustering() function. Use the user-defined number of clusters and ward linkage.  
Add cluster labels to the healthy dataframe.  
Calculate the distances between all instances using SciPy's pdist() function.  
Convert the distance matrix to a square matrix using SciPy's squareform() function.  
Define a clustering model with ward linkage using SciPy's linkage() function.

```python
Ex: If the input is:

4
the output should be:

   sunshine_hours  happiness_levels  labels
0          1858.0              7.44       3
1          2636.0              7.22       0
2          1884.0              7.29       3
3          1821.0              7.35       3
4          1630.0              7.64       3
First five rows of the linkage matrix from SciPy:
 [[39. 40.  0.  2.]
 [28. 43.  0.  3.]
 [ 7. 18.  0.  2.]
 [ 0.  3.  0.  2.]
 [ 8. 42.  0.  2.]]
```


In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# Import needed sklearn packages
# Your code here

# Import needed scipy packages
# Your code here

# Silence warning
import warnings
warnings.filterwarnings('ignore')


In [ ]:
healthy = pd.read_csv('data/healthy_lifestyle.csv')
healthy = healthy.dropna(subset=['sunshine_hours', 'happiness_levels'])

In [ ]:
# Input the number of clusters
number = int(input("Enter the number of clusters: "))

# Define input features
X = healthy[['sunshine_hours', 'happiness_levels']]

In [ ]:
# Use StandardScaler() to standardize input features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=['sunshine_hours', 'happiness_levels'])

In [ ]:
# Initialize and fit an agglomerative clustering model using ward linkage in scikit-learn, with a user-defined
# number of clusters
# Your code here

# Add cluster labels to the healthy dataframe
healthy['labels'] = clustersHealthySklearnFit.labels_
print(healthy[['sunshine_hours', 'happiness_levels', 'labels']].head())

# Perform agglomerative clustering using SciPy
# Calculate the distances between all instances
# Your code here

# Convert the distance matrix to a square matrix
# Your code here

# Define a clustering model with ward linkage
clustersHealthyScipy = # Your code here

print('First five rows of the linkage matrix from SciPy:\n', np.round(clustersHealthyScipy[:5, :], 0))


In [ ]:
# Plot the clusters using matplotlib
plt.figure(figsize=(8, 6))
# Create Scatterplot here
plt.title('Agglomerative Clustering of Healthy Lifestyle Data')
plt.xlabel('Standardized Sunshine Hours')
plt.ylabel('Standardized Happiness Levels')
plt.colorbar(label='Cluster')
plt.show()